apiVersion: apps/v1
kind: Deployment
metadata:
  name: ade-apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ade-apigateway
  template:
    metadata:
      labels:
        app: ade-apigateway
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: ade-apigateway
        image: acradebrmareus.azurecr.io/ade-apigateway:latest
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ade-apigateway
spec:
  ports:
  - port: 80
  selector:
    app: ade-apigateway
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ade-dataingestorservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ade-dataingestorservice
  template:
    metadata:
      labels:
        app: ade-dataingestorservice
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: ade-dataingestorservice
        image: acradebrmareus.azurecr.io/ade-dataingestorservice:latest
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ade-dataingestorservice
spec:
  ports:
  - port: 80
  selector:
    app: ade-dataingestorservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ade-datareporterservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ade-datareporterservice
  template:
    metadata:
      labels:
        app: ade-datareporterservice
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: ade-datareporterservice
        image: acradebrmareus.azurecr.io/ade-datareporterservice:latest
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ade-datareporterservice
spec:
  ports:
  - port: 80
  selector:
    app: ade-datareporterservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ade-frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ade-frontend
  template:
    metadata:
      labels:
        app: ade-frontend
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: ade-frontend
        image: acradebrmareus.azurecr.io/ade-frontend:latest
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ade-frontend
spec:
  type: LoadBalancer
  ports:
  - port: 80
  selector:
    app: ade-frontend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ade-loadtesting-gatling
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ade-loadtesting-gatling
  template:
    metadata:
      labels:
        app: ade-loadtesting-gatling
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: ade-loadtesting-gatling
        image: acradebrmareus.azurecr.io/ade-loadtesting-gatling:latest
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ade-loadtesting-gatling
spec:
  ports:
  - port: 80
  selector:
    app: ade-loadtesting-gatling
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ade-loadtesting-grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ade-loadtesting-grafana
  template:
    metadata:
      labels:
        app: ade-loadtesting-grafana
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: ade-loadtesting-grafana
        image: acradebrmareus.azurecr.io/ade-loadtesting-grafana:latest
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: ade-loadtesting-grafana
spec:
  ports:
  - port: 3000
  selector:
    app: ade-loadtesting-grafana
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ade-loadtesting-influxdb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ade-loadtesting-influxdb
  template:
    metadata:
      labels:
        app: ade-loadtesting-influxdb
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: ade-loadtesting-influxdb
        image: acradebrmareus.azurecr.io/ade-loadtesting-influxdb:latest
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 8083
          name: influxdb-8083
        - containerPort: 8086
          name: influxdb-8086
        - containerPort: 2003
          name: influxdb-2003
---
apiVersion: v1
kind: Service
metadata:
  name: ade-loadtesting-influxdb
spec:
  ports:
  - port: 8083
    name: nginx-8083
  - port: 8086
    name: nginx-8086
  - port: 2003
    name: nginx-2003
  selector:
    app: ade-loadtesting-influxdb
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ade-loadtesting-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ade-loadtesting-redis
  template:
    metadata:
      labels:
        app: ade-loadtesting-redis
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: ade-loadtesting-redis
        image: acradebrmareus.azurecr.io/ade-loadtesting-redis:latest
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: ade-loadtesting-redis
spec:
  ports:
  - port: 6379
  selector:
    app: ade-loadtesting-redis
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ade-userservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ade-userservice
  template:
    metadata:
      labels:
        app: ade-userservice
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: ade-userservice
        image: acradebrmareus.azurecr.io/ade-userservice:latest
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: ade-userservice
spec:
  ports:
  - port: 80
  selector:
    app: ade-userservice
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        env:
        - name: ALLOW_EMPTY_PASSWORD
          value: "yes"
        ports:
        - containerPort: 8080
          name: nginx-8080
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  ports:
  - port: 8080
  selector:
    app: nginx